name: Test Enhanced Weekly Analysis Report

on:
  workflow_dispatch:

jobs:
  test-enhanced-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright
        playwright install chromium

    - name: Create GA4 service account file
      env:
        GA4_SERVICE_ACCOUNT_JSON: ${{ secrets.GA4_SERVICE_ACCOUNT_JSON }}
      run: |
        mkdir -p ga4_service_account
        echo "$GA4_SERVICE_ACCOUNT_JSON" > ga4_service_account/thortful-9a7a7-04cd279e1017.json

    - name: Run enhanced weekly analysis test
      env:
        AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
        AMPLITUDE_SECRET_KEY: ${{ secrets.AMPLITUDE_SECRET_KEY }}
        SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
        GA4_WEB_PROPERTY_ID: ${{ secrets.GA4_WEB_PROPERTY_ID }}
        GA4_APP_PROPERTY_ID: ${{ secrets.GA4_APP_PROPERTY_ID }}
        GA4_SERVICE_ACCOUNT_PATH: ga4_service_account/thortful-9a7a7-04cd279e1017.json
        GA4_ENABLED: true
        APPSFLYER_USERNAME: ${{ secrets.APPSFLYER_USERNAME }}
        APPSFLYER_PASSWORD: ${{ secrets.APPSFLYER_PASSWORD }}
        APPSFLYER_API_TOKEN: ${{ secrets.APPSFLYER_API_TOKEN }}
        APPSFLYER_APP_ID: ${{ secrets.APPSFLYER_APP_ID }}
      run: |
        echo "🚀 Running Enhanced Weekly Analysis Test"
        python enhanced_weekly_analyzer.py

    - name: Upload analysis artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: enhanced-analysis-results
        path: |
          comprehensive_report_*.txt
          appsflyer_data/*/week_*.csv
          *.json
        retention-days: 30

    - name: Commit test results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Test"
        git add -A
        git diff --staged --quiet || git commit -m "Enhanced weekly analysis test - $(date +%Y-%m-%d_%H-%M)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}